[[watcher]]
source = "file"
path = "/sys/class/backlight/intel_backlight/brightness"
max = 19393
tag = "brightness"

[[watcher]]
source = "poll"
command = "wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -d ':' -f2 | xargs | tr -d '\n' | tr -d '.'"
tag = "volume"

[[watcher]]
source = "poll"
command = "wpctl get-volume $(wpctl status | grep 'Streams' -A 10 | grep 'spotify' | cut -d'.' -f1) | cut -d ':' -f2 | xargs | tr -d '\n' | tr -d '.'"
tag = "volume:spotify"
debug = true
