[[watcher]]
source = "file"
path = "/sys/class/backlight/intel_backlight/brightness"
max = 19393
tag = "brightness"

# [[watcher]]
# source = "pipe"
# command = '''
#     stdbuf -oL pactl subscribe | grep --line-buffered "change" | while read -r line; do
#         SINK_IDX=$(echo "$line" | grep -oP 'sink #\K\d+')
#         SINK_INFO=$(pactl list sinks | grep -A 20 "Sink #$SINK_IDX" | awk '/Volume:/ {print $5; exit}')
#         echo "$SINK_INFO" | tr -d '%'
#     done
# '''
# tag = "volume"

[[watcher]]
source = "pipe"
command = "/nix/store/rxzvps8zldnz4sgphbw6893n6ikai6gn-dbus-1.14.10/bin/dbus-monitor \"sender='org.mpris.MediaPlayer2.spotify'\" \\\n    | /nix/store/imad8dvhp77h0pjbckp6wvmnyhp8dpgg-coreutils-9.8/bin/stdbuf -oL /nix/store/x3zjxxz8m4ki88axp0gn8q8m6bldybba-gnugrep-3.12/bin/grep 'string \"Volume\"' -A1 \\\n    | /nix/store/imad8dvhp77h0pjbckp6wvmnyhp8dpgg-coreutils-9.8/bin/stdbuf -oL /nix/store/y2wdhdcrffp9hnkzk06d178hq3g98jay-gawk-5.3.2/bin/awk '/double/ { print $3 }'\n"
tag = "volume:spotify"
debug = true
min = 0
max = 1
